---
tap_install:
  values:
    profile: full
    ceip_policy_disclosed: true

    tap_telemetry:
      installed_for_vmware_internal_use: "true"

    shared:
      ingress_domain: dev.azure.grogscave.net
      image_registry:
        project_path: devcdelashmuttvmware.azurecr.io/tap
    
    supply_chain: testing_scanning

    metadata_store:
      ns_for_export_app_cert: "*"

    image_policy_webhook:
      allow_unmatched_tags: true

    namespace_provisioner:
      additional_sources:
      - git:
          url: https://github.com/cdelashmutt-pivotal/azure-tanzu-gitops.git
          ref: origin/main
          subPath: clusters/dev/namespace-provisioner-resources/objects
        path: _ytt_lib/objects
      - git:
          url: https://github.com/cdelashmutt-pivotal/azure-tanzu-gitops.git
          ref: origin/main
          subPath: clusters/dev/namespace-provisioner-resources/overlays
        path: _ytt_lib/customize
      